name: artifacts creation
on: [push]
jobs:
    upload_artifacts:
       runs-on: ubuntu-latest
       
       env: 
          artifact_name: "log_file"
       steps:
          - name: checkout from repo
            uses: actions/checkout@v4
      
          - name: upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: ${{ env.artifact_name }}
              path: style.css
              


















        
             
          
         
         
